import { User, Customer, PurchaseContract, SupportContract, Ticket, MenuItemId } from './types';

export const initialUsers: User[] = [
  { id: 1, firstName: 'علی', lastName: 'رضایی', username: 'ali.rezaei', password: 'password123', role: 'مدیر', accessibleMenus: ['dashboard', 'customers', 'users', 'contracts', 'tickets', 'reports', 'referrals'] },
  { id: 2, firstName: 'مریم', lastName: 'محمدی', username: 'maryam.mohammadi', password: 'password456', role: 'فروش', accessibleMenus: ['dashboard', 'customers', 'contracts', 'referrals'] },
  { id: 3, firstName: 'حسین', lastName: 'احمدی', username: 'hossein.ahmadi', password: 'password789', role: 'پشتیانی', accessibleMenus: ['dashboard', 'customers', 'tickets', 'referrals'] },
  { id: 4, firstName: 'سارا', lastName: 'کریمی', username: 'sara.karimi', password: 'password101', role: 'برنامه نویس', accessibleMenus: ['dashboard', 'tickets', 'reports', 'referrals'] },
];

export const initialCustomers: Customer[] = [
  {
    id: 1,
    firstName: 'شرکت',
    lastName: 'آلفا',
    nationalId: '1234567890',
    birthDate: '1370/01/01',
    gender: 'مرد',
    maritalStatus: 'متاهل',
    mobileNumbers: ['09123456789'],
    emails: ['alpha@example.com'],
    phone: ['02188888888'],
    address: 'تهران، خیابان اصلی، پلاک ۱',
    jobTitle: 'مدیرعامل',
    companyName: 'شرکت آلفا',
    activityType: 'تولیدی',
    taxCode: 'ECO123',
    bankAccountNumber: '123-456',
    iban: 'IR123456',
    paymentMethods: ['چک', 'حواله'],
    remainingCredit: 1000000,
    softwareType: 'شرکتی',
    purchaseDate: '1402/01/15',
    supportStartDate: '1402/01/20',
    supportEndDate: '1403/01/20',
    level: 'A',
    status: 'فعال',
  },
  {
    id: 2,
    firstName: 'فروشگاه',
    lastName: 'بتا',
    nationalId: '0987654321',
    birthDate: '1365/05/10',
    gender: 'زن',
    maritalStatus: 'مجرد',
    mobileNumbers: ['09112223344'],
    emails: ['beta@example.com'],
    phone: ['03133333333'],
    address: 'اصفهان، میدان نقش جهان',
    jobTitle: 'مدیر فروش',
    companyName: 'فروشگاه بتا',
    activityType: 'خرده فروشی',
    taxCode: 'ECO456',
    bankAccountNumber: '654-321',
    iban: 'IR654321',
    paymentMethods: ['کارت', 'نقد'],
    remainingCredit: 0,
    softwareType: 'فروشگاهی',
    purchaseDate: '1401/11/01',
    supportStartDate: '1401/11/05',
    supportEndDate: '1402/11/05',
    level: 'B',
    status: 'فعال',
  }
];

export const initialPurchaseContracts: PurchaseContract[] = [
    {
        id: 1,
        contractId: 'PC-1402-001',
        contractStartDate: '1402/02/01',
        contractEndDate: '1403/02/01',
        contractDate: '1402/01/25',
        contractType: 'خرید دائم',
        contractStatus: 'فعال',
        softwareVersion: '1.2.0',
        customerType: 'سازمانی',
        customerName: 'شرکت آلفا',
        economicCode: 'ECO123',
        customerAddress: 'تهران، خیابان اصلی، پلاک ۱',
        customerContact: '09123456789',
        customerRepresentative: 'آقای رضایی',
        vendorName: 'شرکت شما',
        salesperson: 'maryam.mohammadi',
        softwareName: 'نرم افزار CRM جامع',
        licenseCount: 10,
        softwareDescription: 'نرم افزار مدیریت ارتباط با مشتریان',
        platform: 'Windows, Web',
        networkSupport: 'بله',
        webMobileSupport: 'دارد',
        initialTraining: '5 ساعت آموزش حضوری',
        setupAndInstallation: 'رایگان',
        technicalSupport: 'یک ساله',
        updates: 'یک ساله رایگان',
        customizations: 'ندارد',
        totalAmount: 50000000,
        prepayment: 20000000,
        paymentStages: 'دو قسط',
        paymentMethods: ['چک'],
        paymentStatus: 'پرداخت شده',
        invoiceNumber: 'INV-101',
        signedContractPdf: 'contract-alpha.pdf',
        salesInvoice: 'invoice-alpha.pdf',
        deliverySchedule: '',
        moduleList: 'ماژول فروش, ماژول پشتیبانی',
        terminationConditions: 'طبق توافقنامه',
        warrantyConditions: 'یک سال',
        ownershipRights: 'متعلق به فروشنده',
        confidentialityClause: 'دارد',
        nonCompeteClause: 'ندارد',
        disputeResolution: 'دادگاه تهران',
        lastStatusChangeDate: '1402/02/01',
        crmResponsible: 'hossein.ahmadi',
        notes: 'مشتری مهمی است.',
        futureTasks: 'پیگیری برای تمدید پشتیبانی در اسفند ماه',
    }
];

export const initialSupportContracts: SupportContract[] = [
    {
        id: 1,
        customerId: 2,
        startDate: '1402/11/05',
        endDate: '1403/11/05',
        duration: 'یکساله',
        supportType: ['تلفنی', 'ریموت'],
        level: 'نقره ای',
        status: 'فعال',
        organizationName: 'فروشگاه بتا',
        contactPerson: 'خانم محمدی',
        contactNumber: '09112223344',
        contactEmail: 'beta@example.com',
        economicCode: 'ECO456',
        fullAddress: 'اصفهان، میدان نقش جهان',
        softwareName: 'نرم افزار حسابداری فروشگاهی',
        softwareVersion: '3.0',
        initialInstallDate: '1401/11/05',
        installType: 'تک کاربره',
        userCount: '1',
        softwareType: 'فروشگاهی',
    },
     {
        id: 2,
        customerId: 1,
        startDate: '1402/01/20',
        endDate: '1403/01/20',
        duration: 'یکساله',
        supportType: ['تلفنی', 'ریموت', 'حضوری'],
        level: 'طلایی',
        status: 'منقضی شده',
        organizationName: 'شرکت آلفا',
        contactPerson: 'آقای رضایی',
        contactNumber: '09123456789',
        contactEmail: 'alpha@example.com',
        economicCode: 'ECO123',
        fullAddress: 'تهران، خیابان اصلی، پلاک ۱',
        softwareName: 'نرم افزار CRM جامع',
        softwareVersion: '1.2.0',
        initialInstallDate: '1402/01/20',
        installType: 'تحت شبکه',
        userCount: '10',
        softwareType: 'شرکتی',
    },
];


export const initialTickets: Ticket[] = [
    {
        id: 1,
        ticketNumber: "T-1403-101",
        title: "مشکل در گزارش گیری فروش",
        description: "گزارش فروش ماهانه خطای SQL میدهد.",
        customerId: 1,
        creationDateTime: "1403/04/01 10:30",
        lastUpdateDate: "1403/04/02 11:45",
        status: "در حال پیگیری",
        priority: "ضطراری",
        type: "خطا",
        channel: "تلفن",
        assignedTo: "hossein.ahmadi",
        attachments: [],
        updates: [
            { id: 1, author: 'hossein.ahmadi', date: '1403/04/01', description: 'تیکت ایجاد و به کاربر ارجاع شد', timeSpent: 5},
            { id: 2, author: 'hossein.ahmadi', date: '1403/04/02', description: 'با مشتری تماس گرفته شد و اطلاعات تکمیلی دریافت شد. در حال بررسی لاگ ها', timeSpent: 30}
        ],
        editableUntil: new Date(0).toISOString(), // Expired
        workSessionStartedAt: new Date().toISOString(), // Currently running for demo
        totalWorkDuration: 2100 // 35 minutes in seconds
    },
    {
        id: 2,
        ticketNumber: "T-1403-102",
        title: "درخواست اضافه کردن فیلد کد پستی",
        description: "لطفا فیلد کد پستی به فرم مشتریان اضافه شود.",
        customerId: 2,
        creationDateTime: "1403/03/20 15:00",
        lastUpdateDate: "1403/03/25 09:10",
        status: "اتمام یافته",
        priority: "متوسط",
        type: "درخواست",
        channel: "پورتال",
        assignedTo: "sara.karimi",
        attachments: ['request-docs.pdf'],
        updates: [],
        editableUntil: new Date(0).toISOString(), // Expired
        totalWorkDuration: 14400, // 4 hours in seconds
    },
     {
        id: 3,
        ticketNumber: "T-1403-103",
        title: "خطای عدم اتصال به پرینتر",
        description: "بعد از آپدیت ویندوز، نرم افزار دیگر پرینتر را شناسایی نمی کند.",
        customerId: 2,
        creationDateTime: "1403/04/05 09:00",
        lastUpdateDate: "1403/04/05 09:00",
        status: "انجام نشده",
        priority: "متوسط",
        type: "مشکل",
        channel: "ایمیل",
        assignedTo: "hossein.ahmadi",
        attachments: [],
        updates: [],
        editableUntil: new Date(Date.now() + 15 * 60 * 1000).toISOString(), // Still editable for demo
        totalWorkDuration: 0,
    }
];
